### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by has256** [rafael-telles/grades-ufabc#1]
Oie, é o Carlos.

Tô (no Uber, hahahaha) revirando o bug que tá fazendo levar pra 404. Acho que na real não é nem código, tenho um palpite bem arbitrário: por acaso tu mudou seu username no Github recentemente? Como a antiga URL era http://raftelti.github.io/grades-ufabc, acho que o link quebrou por isso (talvez precise criar um novo repositório 'username.github.io' também - mas talvez não seja necessário (pelo menos agr é https :octocat:).

Como não é nada que consigo arrumar daqui, só abri a issue, mas qlqr coisa é só avisar!
Abraço!

**Comment by rafael-telles** [comment]
O link novo para a tool é http://rafael-telles.github.io/grades-ufabc/ .
Mas imagino que a mudança do link não crie nenhum problema no funcionamento da ferramenta @el-unicorn

**Comment by has256** [comment]
Nenhuma, tá funcionando perfeitamente! Acho que a galera não tava conseguindo acessar por isso, como eu, tavam usando a url antiga - até esqueci de testar se já tava funcionando no username novo, haha, perdão e mutcho obg!
